CREATE TABLE CLEAN_CLIENTS AS
	SELECT DISTINCT
		COALESCE(NULLIF(TRIM(INITCAP(FIRST_NAME)), ''), 'Missing') AS CLEAN_FIRST_NAME
		,COALESCE(NULLIF(TRIM(INITCAP(LAST_NAME)), ''), 'Missing') AS CLEAN_LAST_NAME
		,COALESCE(NULLIF(TRIM(INITCAP(EMAIL)), ''), 'Missing') AS CLEAN_EMAIL
		,CLEAN_PHONE
		,PHONE_STATUS
	FROM (
		SELECT FIRST_NAME
			, LAST_NAME
			, EMAIL
			, PHONE
			, CASE
				 WHEN CLEAN_PHONE ~ '^(\d)\1{9}$' THEN 'INVALID'
				 WHEN LENGTH(CLEAN_PHONE) = 10 THEN
				 	SUBSTRING(CLEAN_PHONE, 1,3) ||'-'||
					SUBSTRING(CLEAN_PHONE, 4,3) ||'-'||
					SUBSTRING(CLEAN_PHONE, 7,4)
					ELSE 'INVALID'
				END AS CLEAN_PHONE
				
				
			 ,CASE
			 	 WHEN LENGTH(CLEAN_PHONE) > 10 THEN 'NOT_GOOD'
				 WHEN LENGTH(CLEAN_PHONE) < 10 THEN 'NOT_GOOD'
				 WHEN LENGTH(CLEAN_PHONE) = 10 THEN 'GOOD'
				 ELSE ''
			 END PHONE_STATUS
		FROM(
			SELECT FIRST_NAME
				, LAST_NAME
				, EMAIL
				, PHONE
				, COALESCE(NULLIF(TRIM(REGEXP_REPLACE(PHONE, '[^0-9]', '', 'g')), ''), 'Invalid') AS CLEAN_PHONE
			FROM CLIENTS
		) SUB1
	) SUB2


